pragma Singleton
import Quickshell
import Quickshell.Io
import QtQuick
import qs.Services

// The half of the power page that is not tuned: the charge limit, the lid
// action, and the idle timings.
//
// Suspend and screen are ONE editor here on purpose. The timings live in two
// places on a Hyprland desktop -- hypridle's config for blank/lock/suspend, and
// logind's for the lid -- and a user who sets them in two apps ends up with a
// machine that locks at five minutes and suspends at three. The page writes
// both, and hypridle.conf is regenerated wholesale rather than patched, which
// is why it carries a header saying so.
Singleton {
  id: root

  readonly property string rootHelper: "/usr/lib/c7shell/c7power-root"

  // -- charge limit ----------------------------------------------------------
  // Read straight from sysfs, because that is the only thing that knows whether
  // the write took: several vendors clamp the value, and a pack that ignored
  // the request must not show the requested number back.
  readonly property int chargeLimit: limitFile.path === ""
    ? 0 : (parseInt(limitFile.text().trim()) || 0)
  // 100 is the firmware's way of saying "no limit", and so is a missing file.
  readonly property bool limitSupported: limitFile.path !== "" && root.chargeLimit > 0

  FileView {
    id: limitFile
    path: BatteryService.physical?.nativePath
      ? `${BatteryService.physical.nativePath}/charge_control_end_threshold` : ""
    watchChanges: true
    // Most packs do not expose one; that is not a fault worth logging.
    printErrors: false
    onFileChanged: limitFile.reload()
  }

  function setChargeLimit(percent) {
    root.run(["charge-limit", `${Math.round(percent)}`])
  }

  // -- lid -------------------------------------------------------------------
  function setLidClose(action) {
    PowerStore.values.lidClose = action
    root.run(["lid-close", action])
  }

  // -- tuned -----------------------------------------------------------------
  function enableTuned() {
    root.run(["enable-tuned"])
  }

  // pkexec, not sudo: the shell has no terminal to prompt on, and the polkit
  // action names the task rather than the binary. The password panel that
  // answers it is the shell's own (bin/c7-authd).
  function run(args) {
    helper.exec(["pkexec", root.rootHelper].concat(args))
  }

  Process {
    id: helper
    stdout: StdioCollector {}
    stderr: StdioCollector { id: helperErr }
    onExited: code => {
      // 126/127 is the user dismissing the polkit dialog, which is an answer
      // rather than a failure.
      if (code === 0 || code === 126 || code === 127) return
      const why = helperErr.text.trim()
      NotifServer.send("power settings", why !== "" ? why : "the change could not be applied")
    }
  }

  // -- hypridle --------------------------------------------------------------
  // Regenerated from PowerStore whenever a timing changes, then hypridle is
  // restarted: it reads its config once at startup and has no reload.
  //
  // "suspend on battery" is a listener with a condition in front of it, because
  // hypridle has no notion of AC state. /sys/class/power_supply/A*/online is the
  // same file UPower is reading, and `sh -c` is hypridle's own execution model
  // for on-timeout, so this adds no new machinery.
  function hypridleConf() {
    const s = PowerStore
    const lines = [
      "# Generated by the c7shell settings app (system -> power).",
      "# Edit it there: this file is rewritten in full whenever a timing changes.",
      "",
      "general {",
      "    lock_cmd = pidof hyprlock || c7shell-lock",
      "    before_sleep_cmd = loginctl lock-session",
      "}",
      ""
    ]
    if (s.blankScreen > 0) {
      // Blank first, lock `lockAfterBlank` later -- which is what the two rows
      // on the page say, and the opposite of what the shipped hypridle.conf
      // used to do (lock at 5 min, screen off at 5:30). The handoff names the
      // second row "lock after blank", and a label that describes the reverse
      // of what happens is worse than either ordering.
      lines.push("listener {",
                 `    timeout = ${s.blankScreen}`,
                 "    on-timeout = hyprctl dispatch dpms off",
                 "    on-resume = hyprctl dispatch dpms on",
                 "}",
                 "")
      if (s.lockAfterBlank >= 0) {
        lines.push("listener {",
                   `    timeout = ${s.blankScreen + s.lockAfterBlank}`,
                   "    on-timeout = loginctl lock-session",
                   "}",
                   "")
      }
    }
    if (s.suspendOnBattery > 0) {
      lines.push("listener {",
                 `    timeout = ${s.suspendOnBattery}`,
                 "    on-timeout = grep -q 0 /sys/class/power_supply/A*/online && systemctl suspend",
                 "}",
                 "")
    }
    return lines.join("\n")
  }

  FileView {
    id: idleConf
    path: `${Quickshell.env("HOME")}/.config/hypr/hypridle.conf`
    printErrors: false
  }

  function writeHypridle() {
    idleConf.setText(root.hypridleConf())
    // hypridle reads its config once at startup and has no reload, so the only
    // way a new timing takes effect is a restart. Detached, not a Process: the
    // replacement has to outlive this shell process, or restarting the shell
    // would take the machine's idle policy down with it. pkill exits 1 when
    // nothing matched, which is the normal case on a machine where hypridle was
    // never started and is why the `;` is not an `&&`.
    Quickshell.execDetached(["sh", "-c", "pkill -x hypridle; sleep 0.3; exec hypridle"])
  }

  // The page writes PowerStore and the file follows, so the two cannot drift.
  // Debounced: dragging the blank-screen slider would otherwise restart
  // hypridle on every step.
  Connections {
    target: PowerStore
    enabled: PowerStore.ready
    function onBlankScreenChanged() { idleDebounce.restart() }
    function onLockAfterBlankChanged() { idleDebounce.restart() }
    function onSuspendOnBatteryChanged() { idleDebounce.restart() }
  }

  Timer {
    id: idleDebounce
    interval: 600
    onTriggered: root.writeHypridle()
  }
}
