#!/usr/bin/env bash
# The Theme stand-in the qml6 tests run against. Sourced, not executed.
#
# The real Theme pulls in AppearanceStore, which pulls in FileView, which needs
# quickshell proper -- so a test that wants one component in isolation gets this
# instead. Four test scripts each kept their own copy and, between them, had
# drifted: three spellings of text2/text3 and an accentFill written out as
# pre-multiplied floats. This is the one copy.
#
# Its colours come from the same quickshell/c7shell/palette.json the real Theme
# reads, so a token here cannot say something the shell does not.
#
#   write_theme_stub <qs-dir> <shell-src-dir>
#
# Writes <qs-dir>/Theme/Theme.qml and its qmldir. What it declares is the union
# of every token any caller reads: a token no test touches costs nothing, and a
# missing one is a QML warning that fails the run that needed it.
write_theme_stub() {
  local qs=$1 src=$2
  mkdir -p "$qs/Theme"

  # Compiled in rather than read at runtime: plain QtQuick has no FileView, and
  # QML's XMLHttpRequest will not open a local file without
  # QML_XHR_ALLOW_FILE_READ in the environment. Generated fresh on every run, so
  # unlike the greeter's committed copy it cannot go stale.
  "$src/../../tools/gen-palette-qml.py" "$src/palette.json" "$qs/Theme/PaletteStore.qml"

  # Unquoted heredoc: $src is interpolated, and the QML below deliberately
  # contains no other $ or backtick.
  cat > "$qs/Theme/Theme.qml" <<THEME
pragma Singleton
import QtQuick
// Its own module: a qmldir names the singletons in a directory, and naming one
// is not enough to resolve a sibling from inside it.
import qs.Theme

// Generated by tests/fixtures/theme-stub.sh. Not the real Theme -- the tokens
// under test are real, everything around them is the minimum that resolves.
QtObject {
  id: root

  readonly property var palette: PaletteStore.palette
  readonly property var defaults: PaletteStore.defaults

  // Not Theme's JetBrains Mono: the test machine is not required to have it,
  // and a fontconfig substitution warning would fail every run.
  readonly property string fontMono: "monospace"

  readonly property color text: root.palette.text
  readonly property color text2: root.alpha(root.text, 0.55)
  readonly property color text3: root.alpha(root.text, 0.40)
  readonly property color textDisabled: root.alpha(root.text, 0.28)
  readonly property color textOnAccent: root.palette.textOnAccent
  readonly property color success: root.palette.success
  readonly property color warning: root.palette.warning

  readonly property color accent: root.defaults.accent
  readonly property color accentSoft: Qt.hsla(root.accent.hslHue,
                                              root.accent.hslSaturation * 0.90,
                                              Math.min(1, root.accent.hslLightness + 0.108), 1)
  readonly property color accentFill: root.alpha(root.accent, 0.14)
  readonly property color accentBorder: root.alpha(root.accent, 0.30)

  readonly property color glassBase: root.palette.variants.dark.glassBase
  readonly property color bg: root.palette.variants.dark.bg
  readonly property color canvas: root.palette.variants.dark.canvas

  readonly property color surface04: Qt.rgba(1, 1, 1, 0.04)
  readonly property color surface05: Qt.rgba(1, 1, 1, 0.05)
  readonly property color surface07: Qt.rgba(1, 1, 1, 0.07)
  readonly property color surface10: Qt.rgba(1, 1, 1, 0.10)
  readonly property color hairline: Qt.rgba(1, 1, 1, 0.08)
  readonly property color hairlineStrong: Qt.rgba(1, 1, 1, 0.10)
  readonly property color hoverPill: Qt.rgba(1, 1, 1, 0.09)
  readonly property color wellFill: Qt.rgba(0, 0, 0, 0.28)
  readonly property color barShadowColor: Qt.rgba(0, 0, 0, 0.5)
  readonly property color panelShadowColor: Qt.rgba(0, 0, 0, 0.65)

  readonly property real glassAlphaBar: 0.78
  readonly property real glassAlphaPanel: 0.80

  readonly property int radiusPanel: 18
  readonly property int radiusRow: 12
  readonly property int radiusChip: 9
  readonly property int radiusCard: 14
  readonly property int radiusTile: 10
  readonly property int radiusPip: 7

  // The real icons, so an icon this design names but nobody drew is a visible
  // warning here rather than a blank tile on someone's screen.
  readonly property url iconsDir: "file://$src/Assets/icons"

  function alpha(c, a) { return Qt.rgba(c.r, c.g, c.b, a) }
}
THEME

  printf 'module qs.Theme\nsingleton Theme 1.0 Theme.qml\nsingleton PaletteStore 1.0 PaletteStore.qml\n' \
    > "$qs/Theme/qmldir"
}
